name: Dev CI

on:
  push:
    branches:
      - dev

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install this Go version
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Download Go modules
        run: go mod tidy

      - name: Run tests and vet
        run: |
          # do a static analysis of the code recursively from the current directory
          go vet ./...
