# toknow: by default, multiple jobs inside the same xx.yaml file run concurrently, unless explicitly dependencies is defined.
name: CI for main branch

on:
  # manual trigger
  workflow_dispatch: 
  # trigger when push on branch
  push:
    branches:
      - main

jobs:

  display-info-vm:
    uses: abtransitionit/cicd-templates/.github/workflows/runner-vm-info.yaml@main

  display-info-container:
    uses: abtransitionit/cicd-templates/.github/workflows/runner-container-info.yaml@main

  check-code:
    uses: abtransitionit/cicd-templates/.github/workflows/go-check.yaml@main
    with:
      go-version: '1.24'
  
  test-code:
    uses: abtransitionit/cicd-templates/.github/workflows/go-test.yaml@main
    with:
      go-version: '1.24'
