# toknow: by default, multiple jobs inside the same xx.yaml file run concurrently, unless explicitly dependencies is defined.
# purpose: CI specific to main branche
name: CI for main branch

on:
  push:
    branches:
      - main

jobs:
  install-go:
    uses: ./.github/workflows/ci_go-install.yaml

  check-code:
    needs: install-go
    uses: ./.github/workflows/ci_code-check.yaml

  test-code:
    needs: check-code
    uses: ./.github/workflows/ci_code-test.yaml
